name: Deploy Landscape
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: false
        default: master
        description: Enter the tag to deploy
  push:
    branches:
      - 'master'
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Deploy to ~wannec-dozzod-marzod (devstream)"
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }}
          ref: ${{ github.event.inputs.tag }}
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_KEY }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - id: deploy
        name: Deploy
        run:
          ./.github/helpers/deploy.sh tloncorp/landscape garden wannec-dozzod-marnus us-central1-a mainnet-tlon-other-2d ${{ github.event.inputs.tag }}
        env:
          SSH_SEC_KEY: ${{ secrets.GCP_SSH_SEC_KEY }}
          SSH_PUB_KEY: ${{ secrets.GCP_SSH_PUB_KEY }}
          URBIT_REPO_TAG: ${{ vars.URBIT_REPO_TAG }}
